\version "2.18.2"
\language "english"

\header {
    tagline = ##f
}

\layout {}

\paper {}

\score {
    \new Staff
    \with
    {
        \remove Time_signature_engraver
        \remove Bar_engraver
    }
    {
        <<
            \context Voice = "mala voice"
            {
                \voiceOne
                b'1
                c''4
                b'4
                as'4
                c''8
                b'1
                as'8
                b'4
                as'8
                gss'2
                as'8
                c''8
                b'1
                r2
                c''4
                b'1
                c''2
                r16
                ef''16
                r4
                b'1
                as'4
                gss'2
                b'8
                ef''8
                b'1
                r4
                c''16
                b'2
                c''4
                b'2
                ef''8
                b'1
                as'8
                r8
                b'8
                as'8
                gss'2
                b'1
                r2
                c''8
                b'2
                c''16
                b'4
                c''2
                r8
                ef''8
                r8
                c''8
                b'8
                c''4
                b'4
                c''8
                b'16
                ef''16
                gss'2
                r16
                b'16
                ef''16
                b'1
            }
            \context Voice = "vela voice"
            {
                \voiceTwo
                r2
                r4
                f'16
                r2
                ef'8
                r2
                f'16
                r8
                f'16
                r2
                f'16
                gf'8
                ef'16
                r1
                gf'16
                gf'8
                ef'8
                r1
                f'16
                r4
                f'8
                r4
                f'16
                r8
                f'8
                r4
                f'16
                r4
                c'16
                r16
                gf'16
                r1
                f'16
                r1
                gf'4
                r1
                f'16
                r2
                f'8
                r4
                gf'16
                gf'16
                r4
                gf'4
                ef'16
                r2
                f'8
                r4
                r2
                r1
                gf'16
                ef'4
                f'4
                r2
                f'8
                r2
                f'16
                r8
                f'8
                r8
                f'8
                r8
                f'16
                r8
                c'8
                c'16
                r8
                gf'8
                r4
                f'8
                r8
                r2
                gf'16
                r2
                gf'16
                r16
                gf'8
                r1
            }
        >>
    }
}